---
title: "CSL_Producedata"
output: html_document
---


```{r setup, include = FALSE}
set.seed(4609948)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
library(knitr)
opts_chunk$set(echo = FALSE)
library("papaja")
library(dplyr)
library(tidyr)
library(ggplot2)
library(xtable)
library(afex)
library(emmeans)
```

# Behavioural data
```{r organiseBehavData}
#Load day 1 data
day1Behav <- read.table("Behaviour/CSL3D_Behav_Day1.csv",header = TRUE, sep=",")
#Remove eprme junk
day1Behav <- select(day1Behav, -c(Session,DataFile.Basename,AutoResponseWarning,Clock.Information,Display.RefreshRate,ExperimentVersion,RandomSeed,RuntimeCapabilities,RuntimeVersion,RuntimeVersionExpected,SessionDate,SessionStartDateTimeUtc,SessionTime,StudioVersion,TestMode,BlockAccC,BlockAccL,BlockRTC,BlockRTL,pos1,pos2,pos3,pos4,pos5,pos6,pos7,pos8,posColor,posShape,posSingDistr,posTarget,PracticeL,PracticeL.Cycle,PracticeL.Sample,PracticeLC,PracticeLC.Cycle,PracticeLC.Sample,CompSearch.OnsetToOnsetTime,LearnSearch.OnsetToOnsetTime,Response.OnsetToOnsetTime, Response2.OnsetToOnsetTime, Task, Task.Cycle, Task.Sample)
)
#Add session information and a count variable
day1Behav$Session = 1
day1Behav$Count = 1

#Load day 2 data
day2Behav <- read.table("Behaviour/CSL3D_Behav_Day2.csv",header = TRUE, sep=",")
#Remove eprme junk
day2Behav <- select(day2Behav, -c(Session,DataFile.Basename,AutoResponseWarning,Clock.Information,Display.RefreshRate,ExperimentVersion,RandomSeed,RuntimeCapabilities,RuntimeVersion,RuntimeVersionExpected,SessionDate,SessionStartDateTimeUtc,SessionTime,StudioVersion,TestMode,BlockAccC,BlockAccL,BlockRTC,BlockRTL,pos1,pos2,pos3,pos4,pos5,pos6,pos7,pos8,posColor,posShape,posSingDistr,posTarget,PracticeL,PracticeL.Cycle,PracticeL.Sample,CompSearch.OnsetToOnsetTime,LearnSearch.OnsetToOnsetTime,Response.OnsetToOnsetTime, Response2.OnsetToOnsetTime,LC4Blocks, LC4Blocks.Cycle, LC4Blocks.Sample)
)
#Add session information and a count variable
day2Behav$Session = 2
day2Behav$Count = 1

day3Behav <- read.table("Behaviour/CSL3D_Behav_Day3.csv",header = TRUE, sep=",")
#Remove eprme junk
day3Behav <- select(day3Behav, -c(Session,DataFile.Basename,AutoResponseWarning,Clock.Information,Display.RefreshRate,ExperimentVersion,RandomSeed,RuntimeCapabilities,RuntimeVersion,RuntimeVersionExpected,SessionDate,SessionStartDateTimeUtc,SessionTime,StudioVersion,TestMode,BlockAccC,BlockAccL,BlockRTC,BlockRTL,pos1,pos2,pos3,pos4,pos5,pos6,pos7,pos8,posColor,posShape,posSingDistr,posTarget, Task, Task.Cycle, Task.Sample)
)
#Add session information and a count variable
day3Behav$Session = 3
day3Behav$Count = 1

#Bind the 3 sessions together and remove old data
behavData <- rbind(day1Behav, day2Behav, day3Behav)
rm(day1Behav, day2Behav, day3Behav)

#Remove test data subjects
behavData <- filter(behavData, Subject != 99 & Subject != 999)

#Add group assignment information to data
groupData <- read.table("Behaviour/CSL3D_GroupInfo.csv",header = TRUE, sep=",")
for (Subj in c(1:36)) {
    behavData$Group[behavData$Subject==Subj] = groupData$Group[groupData$Subject==Subj]
}
behavData$Group = factor(behavData$Group, labels = c("Colour-Colour", "Colour-Shape", "Shape-Colour","Shape-Shape"))
#behavData$Group = factor(behavData$Group, levels = c("Colour-Colour", "Colour-Shape", "Shape-Shape", "Shape-Colour"))
behavData <- behavData %>% filter(ExperimentName != "CSL 3D Tag1 šbung")
behavData <- behavData %>% mutate(CompSearch.RT = ifelse(is.na(CompSearch.RT), 2000,CompSearch.RT))
behavData <- behavData %>% separate(Group, c("InitSess", "FinSess"), remove = FALSE) %>%
mutate(Session = as.factor(Session), retrain = ifelse(InitSess == FinSess, "Stay", "Switch"), CompCond = ifelse(LateralityComp=="TC" | LateralityComp=="TL","TO", "TD"), InitSess = as.factor(InitSess), FinSess = as.factor(FinSess))
```

```{r summaryTables, include=FALSE}
behavData %>% 
  group_by(Subject, Session) %>%
  summarise(numTrials = sum(Count)) %>%
  spread(Session, numTrials)

behavData %>%
  group_by(Subject, Group) %>%
  summarise(numTrials = sum(Count))
```

```{r createExclusionCriteria}
for (sub in unique(behavData$Subject)) {
  behavData$compSD[behavData$Subject==sub] = sd(filter(behavData,Subject ==sub, Procedure == "TaskC", CompSearch.RT < 2000)$CompSearch.RT)
  behavData$compMean[behavData$Subject==sub] = mean(filter(behavData,Subject ==sub, Procedure == "TaskC", CompSearch.RT < 2000)$CompSearch.RT)
  behavData$learnSD[behavData$Subject==sub] = sd(filter(behavData,Subject ==sub, Procedure == "TaskL", LearnSearch.RT <2000)$LearnSearch.RT)
  behavData$learnMean[behavData$Subject==sub] = mean(filter(behavData,Subject ==sub, Procedure == "TaskL", LearnSearch.RT <2000)$LearnSearch.RT)
}
behavData$compCutoff <- behavData$compMean + (behavData$compSD * 2.5)
behavData$learnCutoff <- behavData$learnMean + (behavData$learnSD * 2.5)

#documenting trial rejection
alltrials <- behavData %>%
  group_by(Subject,Group, Procedure) %>%
  count()
survabrej <- behavData %>%
  filter(LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff) %>%
  group_by(Subject, Group, Procedure) %>%
  count()
survallrej <- behavData %>%
  filter(LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff,LearnSearch.ACC==1 | CompSearch.ACC==1) %>%
  group_by(Subject, Group, Procedure) %>%
  count()
alltrials = cbind(alltrials,two = survabrej$n,three = survallrej$n)
alltrials %>%
  mutate(twoPerc = (n-two)/n*100, threePerc = (two - three)/n*100) %>%
  group_by(Procedure) %>%
  summarise(twomean = mean(twoPerc), threemean = mean(threePerc))
```

```{r behavInitTraining}
cat.acc.init <- behavData %>%
  filter(Procedure == "TaskL", Session == 1, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff) %>%
  group_by(InitSess,Subject) %>%
  summarise(Accuracy = mean(LearnSearch.ACC))
cat.acc.init.aov <- aov_ez(data = cat.acc.init,
                            dv = "Accuracy",
                            id = "Subject",
                            between = c("InitSess")
                            )
cat.rt.init <- behavData %>%
  filter(Procedure == "TaskL", Session == 1, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff, LearnSearch.ACC == 1) %>%
  group_by(InitSess,Subject) %>%
  summarise(ResponseTime = mean(LearnSearch.RT))
cat.rt.init.aov <- aov_ez(data = cat.rt.init,
                          dv = "ResponseTime",
                          id = "Subject",
                          between = c("InitSess")
                          )
srch.acc.init <- behavData %>%
  filter(Procedure == "TaskC", Session == 1, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff) %>%
  group_by(InitSess,CompCond,Subject) %>%
  summarise(Accuracy = mean(CompSearch.ACC))
srch.acc.init.aov <- aov_ez(data = srch.acc.init,
                            dv = "Accuracy",
                            id = "Subject",
                            within = c("CompCond"),
                            between = c("InitSess")
                            )
srch.rt.init <- behavData %>%
  filter(Procedure == "TaskC", Session == 1, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff, CompSearch.ACC == 1) %>%
  group_by(InitSess,CompCond,Subject) %>%
  summarise(ResponseTime = mean(CompSearch.RT))
srch.rt.init.aov <- aov_ez(data = srch.rt.init,
                           dv = "ResponseTime",
                           id = "Subject",
                           within = c("CompCond"),
                           between = c("InitSess")
                           )
distint.init <- behavData %>%
  filter(Procedure == "TaskC", Session == 1, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff, CompSearch.ACC == 1) %>%
  group_by(InitSess,CompCond,Subject) %>%
  summarise(ResponseTime = mean(CompSearch.RT)) %>%
  spread(CompCond, ResponseTime) %>%
  mutate(DistractorInterference = TD - TO)
distint.init.aov <- aov_ez(data = distint.init,
                           dv = "DistractorInterference",
                           id = "Subject",
                           between = c("InitSess")
                           )
```

```{r behavExtdTraining}
cat.acc.extd <- behavData %>%
  filter(Procedure == "TaskL", Session != 2, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff, InitSess == FinSess) %>%
  group_by(InitSess,Session, Subject) %>%
  summarise(Accuracy = mean(LearnSearch.ACC))
cat.acc.extd.aov <- aov_ez(data = cat.acc.extd,
                            dv = "Accuracy",
                            id = "Subject",
                            within = c("Session"),
                            between = c("InitSess")
                            )
cat.rt.extd <- behavData %>%
  filter(Procedure == "TaskL", Session != 2, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff, InitSess == FinSess, LearnSearch.ACC == 1) %>%
  group_by(InitSess,Session,Subject) %>%
  summarise(ResponseTime = mean(LearnSearch.RT))
cat.rt.extd.aov <- aov_ez(data = cat.rt.extd,
                          dv = "ResponseTime",
                          id = "Subject",
                          within = c("Session"),
                          between = c("InitSess")
                          )
srch.acc.extd <- behavData %>%
  filter(Procedure == "TaskC", Session != 2, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff, InitSess == FinSess) %>%
  group_by(InitSess,Session,CompCond,Subject) %>%
  summarise(Accuracy = mean(CompSearch.ACC))
srch.acc.extd.aov <- aov_ez(data = srch.acc.extd,
                            dv = "Accuracy",
                            id = "Subject",
                            within = c("Session","CompCond"),
                            between = c("InitSess")
                            )
srch.rt.extd <- behavData %>%
  filter(Procedure == "TaskC", Session != 2, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff, InitSess == FinSess, CompSearch.ACC == 1) %>%
  group_by(InitSess,Session,CompCond,Subject) %>%
  summarise(ResponseTime = mean(CompSearch.RT))
srch.rt.extd.aov <- aov_ez(data = srch.rt.extd,
                           dv = "ResponseTime",
                           id = "Subject",
                           within = c("Session","CompCond"),
                           between = c("InitSess")
                           )

distint.extd <- behavData %>%
  filter(Procedure == "TaskC", Session != 2, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff, InitSess == FinSess, CompSearch.ACC == 1) %>%
  group_by(InitSess,Session,CompCond,Subject) %>%
  summarise(ResponseTime = mean(CompSearch.RT)) %>%
  spread(CompCond, ResponseTime) %>%
  mutate(DistractorInterference = TD - TO)
distint.extd.aov <- aov_ez(data = distint.extd,
                           dv = "DistractorInterference",
                           id = "Subject",
                           within = c("Session"),
                           between = c("InitSess")
                           )
distint.extd.emmeans <- emmeans(distint.extd.aov, ~InitSess*Session)
distint.extd.posthoc <- pairs(distint.extd.emmeans)
```

```{r behavRetrTraining}
cat.acc.retr <- behavData %>%
  filter(Procedure == "TaskL", Session == 3, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff) %>%
  group_by(retrain,FinSess, Subject) %>%
  summarise(Accuracy = mean(LearnSearch.ACC))
cat.acc.retr.aov <- aov_ez(data = cat.acc.retr,
                            dv = "Accuracy",
                            id = "Subject",
                            between = c("retrain","FinSess")
                            )
cat.rt.retr <- behavData %>%
  filter(Procedure == "TaskL", Session == 3, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff, LearnSearch.ACC == 1) %>%
  group_by(retrain,FinSess,Subject) %>%
  summarise(ResponseTime = mean(LearnSearch.RT))
cat.rt.retr.aov <- aov_ez(data = cat.rt.retr,
                          dv = "ResponseTime",
                          id = "Subject",
                          between = c("retrain","FinSess")
                          )
srch.acc.retr <- behavData %>%
  filter(Procedure == "TaskC", Session == 3, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff) %>%
  group_by(retrain,FinSess,CompCond,Subject) %>%
  summarise(Accuracy = mean(CompSearch.ACC))
srch.acc.retr.aov <- aov_ez(data = srch.acc.retr,
                            dv = "Accuracy",
                            id = "Subject",
                            within = c("CompCond"),
                            between = c("retrain","FinSess")
                            )
srch.rt.retr <- behavData %>%
  filter(Procedure == "TaskC", Session == 3, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff, CompSearch.ACC == 1) %>%
  group_by(FinSess,retrain,CompCond,Subject) %>%
  summarise(ResponseTime = mean(CompSearch.RT))
srch.rt.retr.aov <- aov_ez(data = srch.rt.retr,
                           dv = "ResponseTime",
                           id = "Subject",
                           within = c("CompCond"),
                           between = c("retrain","FinSess")
                           )
distint.retr <- behavData %>%
  filter(Procedure == "TaskC", Session == 3, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff, CompSearch.ACC == 1) %>%
  group_by(FinSess,retrain,CompCond,Subject) %>%
  summarise(ResponseTime = mean(CompSearch.RT)) %>%
  spread(CompCond, ResponseTime) %>%
  mutate(DistractorInterference = TD - TO)
distint.retr.aov <- aov_ez(data = distint.retr,
                           dv = "DistractorInterference",
                           id = "Subject",
                           between = c("retrain","FinSess")
                           )
```

```{r saveBehavData}
save(cat.acc.init.aov, cat.rt.init.aov, srch.acc.init.aov, srch.rt.init.aov,distint.init.aov, cat.acc.extd.aov, cat.rt.extd.aov, srch.acc.extd.aov, srch.rt.extd.aov, distint.extd.aov, distint.extd.posthoc, cat.acc.retr.aov, cat.rt.retr.aov, srch.acc.retr.aov, srch.rt.retr.aov, distint.retr.aov, file = "DataOutput/behavANOVAs.RData")
```

```{r behavPlots}
behavData %>%
  filter(Procedure == "TaskL", Session != 2, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff) %>%
  mutate(Session = as.factor(Session)) %>%
  group_by(Group, Session,Subject) %>%
  summarise(Accuracy = mean(LearnSearch.ACC)) %>%
  mutate(se = sd(Accuracy)/sqrt(9))%>%
  group_by(Group,Session)%>%
  summarise(Accuracy = mean(Accuracy)*100, se = mean(se)*100) %>%
  ggplot(., aes(Session, Accuracy)) +
  geom_bar(stat = "identity") +
  facet_grid(.~Group) +
  geom_errorbar(aes(ymin = Accuracy-se, ymax = Accuracy+se), width = .2) +
  coord_cartesian(ylim=c(75,100))+
  theme_apa()
ggsave('Figures/Behav1.jpg',width=5, height=4, units="in", dpi = 300)

behavData %>%
  filter(Procedure == "TaskL", Session != 2, LearnSearch.ACC==1, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff) %>%
  mutate(Session = as.factor(Session)) %>%
  group_by(Group, Session,Subject) %>%
  summarise(ResponseTime = mean(LearnSearch.RT)) %>%
  mutate(se = sd(ResponseTime)/sqrt(9))%>%
  group_by(Group,Session)%>%
  summarise(ResponseTime = mean(ResponseTime), se = mean(se)) %>%
  ggplot(., aes(Session, ResponseTime)) +
  geom_bar(stat = "identity") +
  facet_grid(.~Group) +
  geom_errorbar(aes(ymin = ResponseTime-se, ymax = ResponseTime+se), width = .2) +
  coord_cartesian(ylim=c(400,800))+
  theme_apa()
ggsave('Figures/Behav2.jpg',width=5, height=4, units="in", dpi = 300)

behavData %>%
  filter(Procedure == "TaskC", Session != 2, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff) %>%
  mutate(Session = as.factor(Session), CompCond = ifelse(LateralityComp=="TC" | LateralityComp=="TL","TO", "TD")) %>%
  group_by(Group, Session, CompCond,Subject) %>%
  summarise(Accuracy = mean(CompSearch.ACC)) %>%
  mutate(se = sd(Accuracy)/sqrt(9))%>%
  group_by(Group,Session,CompCond)%>%
  summarise(Accuracy = mean(Accuracy)*100, se = mean(se)*100) %>%
  ggplot(., aes(x = Session, y = Accuracy, group = CompCond, fill=CompCond)) +
  geom_bar(position = "dodge", stat = "identity") +
  facet_grid(.~Group) +
  geom_errorbar(aes(ymin = Accuracy-se, ymax = Accuracy+se), width = .2, position=position_dodge(.9)) +
  coord_cartesian(ylim=c(75,100))+
  theme_apa()
ggsave('Figures/Behav3.jpg',width=5, height=4, units="in", dpi = 300)

behavData %>%
  filter(Procedure == "TaskC", Session != 2, CompSearch.ACC==1, LearnSearch.RT < learnCutoff | CompSearch.RT < compCutoff) %>%
  mutate(Session = as.factor(Session), CompCond = ifelse(LateralityComp=="TC" | LateralityComp=="TL","TO", "TD")) %>%
  group_by(Group, Session, CompCond,Subject) %>%
  summarise(ResponseTime = mean(CompSearch.RT)) %>%
  mutate(se = sd(ResponseTime)/sqrt(9))%>%
  group_by(Group,Session,CompCond)%>%
  summarise(ResponseTime = mean(ResponseTime), se = mean(se)) %>%
  ggplot(., aes(x = Session, y = ResponseTime, group = CompCond, fill=CompCond)) +
  geom_bar(position = "dodge", stat = "identity") +
  facet_grid(.~Group) +
  geom_errorbar(aes(ymin = ResponseTime-se, ymax = ResponseTime+se), width = .2, position = position_dodge(.9)) +
  scale_fill_manual(values=c("red4", "gray42"))+
  coord_cartesian(ylim=c(500,800))+
  theme_apa() +
  theme(#legend.position = "None",
        axis.line = element_line(colour = "black"))
ggsave('Figures/Behav4.jpg',width=5, height=4, units="in", dpi = 300)

behavData %>%
  filter(Procedure == "TaskC", Session != 2, CompSearch.ACC==1) %>%
  mutate(Session = as.factor(Session), CompCond = ifelse(LateralityComp=="TC" | LateralityComp=="TL","TO", "TD")) %>%
  group_by(Group, Session, CompCond, Subject) %>%
  summarise(ResponseTime = mean(CompSearch.RT)) %>%
  spread(CompCond, ResponseTime) %>%
  mutate(DistractorInterference = TD - TO) %>%
  mutate(se = sd(DistractorInterference)/9) %>%
  group_by(Group, Session) %>%
  summarise(DistractorInterference = mean(DistractorInterference), se = mean(se)) %>%
  ggplot(., aes(Session, DistractorInterference)) +
  geom_bar(stat = "identity", fill = "turquoise4") +
  facet_grid(.~Group) +
  geom_errorbar(aes(ymin = DistractorInterference-se, ymax = DistractorInterference+se), width = .2) +
  theme_apa() +
  theme(text= element_blank(),
          strip.text.y = element_blank(),
          strip.text.x = element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          legend.position = "None")
```


# EEG data
```{r organiseData}
dPath = 'EEG/Visuals/'
fPrefix = 'N2pc'

#Load group data
groupdata = read.csv(file="Behaviour/CSL3D_GroupInfo.csv")

#####
#Creates aggregate of all participant data (needs dPath and fPrefix)
eFilePattern = paste(fPrefix,"*_epochs.csv", sep="")
lFilePattern = paste(fPrefix,"*_LH.csv", sep="")
rFilePattern = paste(fPrefix,"*_RH.csv", sep="")
eFileList = list.files(dPath, pattern=glob2rx(eFilePattern))
lFileList = list.files(dPath, pattern=glob2rx(lFilePattern))
rFileList = list.files(dPath, pattern=glob2rx(rFilePattern))

#create variables using first dataset
epochInfo = read.csv(file = paste(dPath,eFileList[1], sep=""))
epochInfo$Subject = 1
epochInfo$Group = groupdata$Group[1]
lHemData = read.csv(file = paste(dPath,lFileList[1], sep=""), header = FALSE)
rHemData = read.csv(file = paste(dPath,rFileList[1], sep=""), header = FALSE)
#append the other datasets to the above variables
for (subj in 2:length(eFileList)) {
  curEpochInfo = read.csv(file = paste(dPath,eFileList[subj], sep=""))
  curEpochInfo$Subject = subj
  curEpochInfo$Group = groupdata$Group[subj]
  curLHemData = read.csv(file = paste(dPath,lFileList[subj], sep=""), header = FALSE)
  curRHemData = read.csv(file = paste(dPath,rFileList[subj], sep=""), header = FALSE)
  
  epochInfo = rbind(epochInfo, curEpochInfo)
  lHemData = rbind(lHemData, curLHemData)
  rHemData = rbind(rHemData, curRHemData)
}
#Tidy the variables, remove unnecessary and convert to factors
epochInfo$Subject = as.factor(epochInfo$Subject)

#clear stuff that I don't need
rm(curEpochInfo,curLHemData,curRHemData, fPrefix, eFileList, eFilePattern, lFileList, lFilePattern, rFileList, rFilePattern, subj, groupdata)
gc()
#####
#Permutation can be done at this stage using epochInfo$Hemifield = sample(epochInfo$Hemifield, replace=FALSE)
#combine all the data together into one long table
gathercols = colnames(lHemData)
lHemData$Hem = "Left"
rHemData$Hem = "Right"
scalpData = rbind(lHemData,rHemData)
origEpochInfo = rbind(epochInfo,epochInfo)

allData <- cbind(origEpochInfo, scalpData)
allData <- gather(allData, "sample", "voltage", gathercols, factor_key = TRUE)

#Tidy variable names etc. and create any necessary variables - could use unite
allData$sample <- as.integer(substring(allData$sample,2))
allData <- allData %>% mutate(Contra = ifelse(Hemifield==Hem, "Ipsilateral", "Contralateral"))
allData <- allData %>% mutate(Stimulus = as.factor(paste(LatStim," (",MidStim," mid)", sep = "")))

#clear stuff that I don't need
rm(origEpochInfo,scalpData,epochInfo, lHemData, rHemData)
gc()
#Change factor labels
allData <-  mutate(allData, Group1 = substr(allData$Group,1,1))
allData <-  mutate(allData, Group2 = substr(allData$Group,2,2))
allData <-  mutate(allData, GroupP = ifelse(Group1 == Group2, "Unchanged", "Changed"))
allData <-  mutate(allData, Contra = ifelse(Hemifield == Hem, "Ipsilateral", "Contralateral"))

allData$Group = factor(allData$Group, labels = c("Colour-Colour", "Colour-Shape", "Shape-Colour", "Shape-Shape"))
allData$Group = factor(allData$Group, levels = c("Colour-Colour", "Shape-Colour", "Shape-Shape", "Colour-Shape"))
allData$Stimulus = factor(allData$Stimulus, levels = c("Color (Shape mid)", "Shape (Color mid)", "Target (None mid)", "Target (Distractor mid)", "Distractor (Target mid)","None (Target mid)"))
allData$Group  <- as.factor(allData$Group)
allData$Group1 <- as.factor(allData$Group1)
allData$Group2 <- as.factor(allData$Group2)
allData$GroupP <- as.factor(allData$GroupP)
gc()
```

```{r setParams}
baseline = 200
plotWidth = 24
plotHeight = 9

NtStart = 150
NtEnd = 250
PdStart = 250
PdEnd = 350
```

```{r trialCount}
print(
  xtable(allData %>%
    filter(Event == "Learn",sample == 1, Contra == 'Contralateral') %>%
    group_by(Subject,LatStim) %>%
    summarise(trialCount = sum(sample)) %>%
      spread(LatStim,trialCount)
  ,digits = 0)
,include.rownames = FALSE, comment = FALSE)

print(
  xtable(allData %>%
    filter(Event == "Search",sample == 1, Contra == 'Contralateral') %>%
    group_by(Subject,LatStim,Group) %>%
    summarise(trialCount = sum(sample)) %>%
      spread(LatStim,trialCount)
  ,digits = 0)
,include.rownames = FALSE, comment = FALSE)
```

## Search Task

### Initial Training
```{r, findInitSrchCompWindows}
grandTarget <- allData %>%
  filter( Event == "Learn" & LatStim == "Predictor" & searchRej == 0) %>%
  mutate(sample = sample*srateMultiplier-baseline) %>%
  filter(sample > 200) %>%
  group_by(sample,Contra) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral)
NtStart = grandTarget$sample[grandTarget$diff == min(grandTarget$diff)]-winSize/2
NtEnd = grandTarget$sample[grandTarget$diff == min(grandTarget$diff)]+winSize/2
grandDist <- allData %>%
  filter( Event == "Learn" & LatStim == "NonPred" & searchRej == 0) %>%
  mutate(sample = sample*srateMultiplier-baseline) %>%
  filter(sample > 200) %>%
  group_by(sample,Contra) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral)
PdStart = grandDist$sample[grandDist$diff == max(grandDist$diff)]-winSize/2
PdEnd = grandDist$sample[grandDist$diff == max(grandDist$diff)]+winSize/2
```

#### Target Lateralised

#### Distractor Lateralised

### Extended training effects

#### Target Lateralised

#### Distractor Lateralised

### Retraining effects

#### Target Lateralised

#### Distractor Lateralised

## Pre-move code
```{r}

allData %>%
  filter(Event == "Learn", Session == "Day1", LatStim != "None", Subject != 20) %>%
  mutate(sample = sample-baseline) %>%
  group_by(LatStim,sample,Contra,Group1) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_rect(xmin = 150, xmax = 250, ymin = Inf, ymax = 0, fill = "mistyrose1") +
    geom_rect(xmin = 250, xmax = 350, ymin = -Inf, ymax = 0, fill = "mistyrose1") +
    geom_line(aes(colour = Group1),size=3) +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(.~LatStim) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(10, "lines"), text= element_text(size=50))
ggsave("learnDay1.pdf", width = 40, height =10)

#####
allData %>%
  filter(Event == "Learn", Session == "Day3", LatStim != "None", Subject != 20) %>%
  mutate(sample = sample*2-baseline) %>%
  group_by(LatStim,sample,Contra,Group2) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_line(aes(colour = Group2),size=0.5) +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(LatStim~.) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(2, "lines"), text= element_text(size=12))

allData %>%
  filter(Event == "Learn", Session == "Day1", LatStim != "None", Subject != 20) %>%
  mutate(sample = sample*2-baseline) %>%
  group_by(LatStim,sample,Contra,GroupP) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_line(aes(colour = GroupP),size=0.5) +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(LatStim~.) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(2, "lines"), text= element_text(size=12))

allData %>%
  filter(Event == "Learn", Session == "Day3", LatStim != "None", Subject != 20) %>%
  mutate(sample = sample*2-baseline) %>%
  group_by(LatStim,sample,Contra,GroupP) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_line(aes(colour = GroupP),size=0.5) +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(LatStim~.) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(2, "lines"), text= element_text(size=12))

allData %>%
  filter(Event == "Learn", Session == "Day3", LatStim != "None", Subject != 20) %>%
  mutate(sample = sample-baseline) %>%
  group_by(LatStim,sample,Contra,Group) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_line(aes(colour = Group),size=0.5) +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(LatStim~.) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(2, "lines"), text= element_text(size=12))
#####
allData %>%
  filter(Event == "Learn", LatStim != "None", Subject != 20) %>%
  mutate(sample = sample-baseline) %>%
  group_by(Session, LatStim,sample,Contra,Group) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_rect(xmin = 150, xmax = 250, ymin = Inf, ymax = 0, fill = "mistyrose1") +
    geom_rect(xmin = 250, xmax = 350, ymin = -Inf, ymax = 0, fill = "mistyrose1") +
    geom_line(aes(colour = Session),size=3) +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(Group~LatStim) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(10, "lines"), text= element_text(size=50))
ggsave("learnAll.pdf", width = 40, height = 30)
```

```{r learnStats}
#Nt
nt.learn.day1 <- allData %>%
  filter(Event == "Learn", Session == "Day1", LatStim != "None", Subject != 20) %>%
  mutate(sample = sample-baseline) %>%
  filter(sample>NtStart & sample <NtEnd) %>%
  group_by(Subject, LatStim,Contra,Group1) %>%
  summarise(mV = mean(voltage)) %>%
  spread(Contra, mV) %>% 
  mutate(diff = Contralateral - Ipsilateral)
nt.learn.day1.aov <- aov_ez(data = nt.learn.day1,
                            dv = "diff",
                            id = "Subject",
                            within = c("LatStim"),
                            between = c("Group1")
                            )
#nt.learn.day1.results <- apa_print(nt.learn.day1.aov)
nt.learn.day1.emmeans <- emmeans(nt.learn.day1.aov, ~Group1*LatStim)
nt.learn.day1.posthoc <- pairs(nt.learn.day1.emmeans)

pd.learn.day1 <- allData %>%
  filter(Event == "Learn", Session == "Day1", LatStim != "None", Subject != 20) %>%
  mutate(sample = sample-baseline) %>%
  filter(sample>PdStart & sample <PdEnd) %>%
  group_by(Subject, LatStim,Contra,Group1) %>%
  summarise(mV = mean(voltage)) %>%
  spread(Contra, mV) %>% 
  mutate(diff = Contralateral - Ipsilateral)
pd.learn.day1.aov <- aov_ez(data = pd.learn.day1,
                            dv = "diff",
                            id = "Subject",
                            within = c("LatStim"),
                            between = c("Group1")
                            )


nt.learn <- allData %>%
  filter(Event == "Learn", LatStim == "Shape", Subject != 20) %>%
  mutate(sample = sample-baseline) %>%
  filter(sample>NtStart & sample <NtEnd) %>%
  group_by(Session,Subject,Contra,Group1, GroupP) %>%
  summarise(mV = mean(voltage)) %>%
  spread(Contra, mV) %>% 
  mutate(diff = Contralateral - Ipsilateral)
nt.learn.aov <- aov_ez(data = nt.learn,
                            dv = "diff",
                            id = "Subject",
                            within = c("Session"),
                            between = c("Group1", "GroupP")
                            )
nt.learn.emmeans <- emmeans(nt.learn.aov, ~Group1*GroupP*Session)
nt.learn.posthoc <- pairs(nt.learn.emmeans)

pd.learn <- allData %>%
  filter(Event == "Learn", LatStim == "Shape", Subject != 20) %>%
  mutate(sample = sample-baseline) %>%
  filter(sample>PdStart & sample <PdEnd) %>%
  group_by(Session,Subject,Contra,Group1, GroupP) %>%
  summarise(mV = mean(voltage)) %>%
  spread(Contra, mV) %>% 
  mutate(diff = Contralateral - Ipsilateral)
pd.learn.aov <- aov_ez(data = pd.learn,
                            dv = "diff",
                            id = "Subject",
                            within = c("Session"),
                            between = c("Group1", "GroupP")
                            )
```

```{r setParams}
baseline = 200
plotWidth = 24
plotHeight = 9

NtStart = 200
NtEnd = 275
PdStart = 275
PdEnd = 350
```

```{r}

allData %>%
  filter(Event == "Search", Session == "Day1", LatStim != "None") %>%
  mutate(sample = sample-baseline) %>%
  group_by(Stimulus,sample,Contra,Group1) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_rect(aes(xmin = NtStart, xmax = NtEnd, ymin = -Inf, ymax = 0), fill = "lemonchiffon") + 
    geom_rect(data = . %>% filter(Stimulus  == "Distractor (Target mid)"),aes(xmin = PdStart, xmax = PdEnd, ymin = 0, ymax = Inf), fill = "lemonchiffon") +
    geom_line(aes(colour = Group1),size=3) +
    scale_color_manual(values=c("green4", "gray42"))+
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    coord_cartesian(ylim=c(-2,2))+
    facet_grid(.~Stimulus) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(10, "lines"), 
          text= element_text(size=50),
          legend.position = "None")
ggsave("searchDay1.pdf", width = 40, height = 10)
#####
allData %>%
  filter(Event == "Search", Session == "Day3", LatStim != "None") %>%
  mutate(sample = sample*2-baseline) %>%
  group_by(LatStim,sample,Contra,Group2) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_line(aes(colour = Group2),size=0.5) +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(LatStim~.) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(2, "lines"), text= element_text(size=12))

allData %>%
  filter(Event == "Search", Session == "Day1", LatStim != "None") %>%
  mutate(sample = sample*2-baseline) %>%
  group_by(LatStim,sample,Contra,GroupP) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_line(aes(colour = GroupP),size=0.5) +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(LatStim~.) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(2, "lines"), text= element_text(size=12))

allData %>%
  filter(Event == "Search", Session == "Day3", LatStim != "None") %>%
  mutate(sample = sample*2-baseline) %>%
  group_by(LatStim,sample,Contra,GroupP) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_line(aes(colour = GroupP),size=0.5) +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(LatStim~.) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(2, "lines"), text= element_text(size=12))

allData %>%
  filter(Event == "Search", Session == "Day1", LatStim != "None", Subject != 20) %>%
  mutate(sample = sample-baseline) %>%
  group_by(LatStim,sample,Contra,Group) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_line(aes(colour = Group),size=0.5) +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(LatStim~.) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(2, "lines"), text= element_text(size=12))

allData %>%
  filter(Event == "Search",  LatStim != "None", Subject != 20, Subject !=16) %>%
  mutate(sample = sample-baseline) %>%
  group_by(Session, Stimulus,sample,Contra,Group) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_line(aes(colour = Group),size=1) +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(Session~Stimulus) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(2, "lines"), text= element_text(size=30))
ggsave("TESTPLOT.pdf", width = 40, height = 20)

allData %>%
  filter(Event == "Search",  Session == "Day1", Stimulus == "Distractor (Target mid)", Subject != 20, Subject !=16) %>%
  mutate(sample = sample-baseline) %>%
  group_by(Subject, Stimulus,sample,Contra,Group) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_line(aes(colour = Subject),size=1) +
    #scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(Group~.) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(2, "lines"), text= element_text(size=30))
ggsave("indvSubj.pdf", width = 20, height = 45)
#####
allData %>%
  filter(Event == "Search",  LatStim != "None", Subject != 20, Subject !=16, Group == "Colour-Colour" | Group == "Shape-Shape") %>%
  mutate(sample = sample-baseline) %>%
  group_by(Session, Stimulus,sample,Contra,Group) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
      geom_rect(xmin = NtStart, xmax = NtEnd, ymin = Inf, ymax = 0, fill = "lemonchiffon") +
    geom_rect(data = . %>% filter(Stimulus  == "Distractor (Target mid)"),xmin = PdStart, xmax = PdEnd, ymin = -Inf, ymax = 0, fill = "lemonchiffon") +
    geom_line(aes(colour = Session),size=3) +
    scale_color_manual(values=c("gray42", "royalblue"))+
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(Group~Stimulus) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(10, "lines"), 
          text= element_text(size=50),
          legend.position = "None")
ggsave("searchAlltraining.pdf", width = 40, height = 20)

allData %>%
  filter(Event == "Search",  LatStim != "None", Subject != 20, Subject !=16, Group == "Colour-Colour" | Group == "Shape-Colour") %>%
  mutate(sample = sample-baseline) %>%
  group_by(Session, Stimulus,sample,Contra,Group) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
      geom_rect(xmin = NtStart, xmax = NtEnd, ymin = Inf, ymax = 0, fill = "lemonchiffon") +
    geom_rect(data = . %>% filter(Stimulus  == "Distractor (Target mid)"),xmin = PdStart, xmax = PdEnd, ymin = -Inf, ymax = 0, fill = "lemonchiffon") +
    geom_line(aes(colour = Session),size=3) +
    scale_color_manual(values=c("gray42", "royalblue"))+
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(Group~Stimulus) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(10, "lines"), 
          text= element_text(size=50),
          legend.position = "None")
ggsave("searchAllColourFinishers.pdf", width = 40, height = 20)

allData %>%
  filter(Event == "Search",  LatStim != "None", Subject != 20, Subject !=16, Group == "Shape-Shape" | Group == "Colour-Shape") %>%
  mutate(sample = sample-baseline) %>%
  group_by(Session, Stimulus,sample,Contra,Group) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
      geom_rect(xmin = NtStart, xmax = NtEnd, ymin = Inf, ymax = 0, fill = "lemonchiffon") +
    geom_rect(data = . %>% filter(Stimulus  == "Distractor (Target mid)"),xmin = PdStart, xmax = PdEnd, ymin = -Inf, ymax = 0, fill = "lemonchiffon") +
    geom_line(aes(colour = Session),size=3) +
    scale_color_manual(values=c("gray42", "royalblue"))+
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(Group~Stimulus) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(10, "lines"), 
          text= element_text(size=50),
          legend.position = "None")
ggsave("searchAllShapeFinishers.pdf", width = 40, height = 20)

allData %>%
  filter(Event == "Search",  LatStim != "None", Subject != 20, Subject !=16, Session == "Day3") %>%
  mutate(sample = sample-baseline) %>%
  group_by(Session, Stimulus,sample,Contra,GroupP,Group2) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
      geom_rect(xmin = NtStart, xmax = NtEnd, ymin = Inf, ymax = 0, fill = "lemonchiffon") +
    geom_rect(data = . %>% filter(Stimulus  == "Distractor (Target mid)"),xmin = PdStart, xmax = PdEnd, ymin = -Inf, ymax = 0, fill = "lemonchiffon") +
    geom_line(aes(colour = GroupP),size=3) +
    scale_color_manual(values=c("navyblue", "dodgerblue"))+
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(Group2~Stimulus) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(10, "lines"), 
          text= element_text(size=50)
          #,legend.position = "None"
          )
ggsave("search3HistoryChange.pdf", width = 40, height = 20)

allData %>%
  filter(Event == "Search",  LatStim != "None", Subject != 20, Subject !=16) %>%
  mutate(sample = sample-baseline, CatStim = as.factor(ifelse(Group1==Group2,Group1,Group2))) %>%
  group_by( Stimulus,sample,Contra,GroupP,CatStim) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
      geom_rect(xmin = NtStart, xmax = NtEnd, ymin = Inf, ymax = 0, fill = "lemonchiffon") +
    geom_rect(data = . %>% filter(Stimulus  == "Distractor (Target mid)"),xmin = PdStart, xmax = PdEnd, ymin = -Inf, ymax = 0, fill = "lemonchiffon") +
    geom_line(aes(colour = GroupP),size=3) +
    scale_color_manual(values=c("gray42", "dodgerblue"))+
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(CatStim~Stimulus) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(10, "lines"), 
          text= element_text(size=50)
          #,legend.position = "None"
          )
ggsave("search1and3HistoryChange.pdf", width = 40, height = 20)

allData %>%
  filter(Event == "Search",  LatStim != "None", Subject != 20, Subject !=16, Session == "Day3") %>%
  mutate(sample = sample-baseline) %>%
  group_by(Session, Stimulus,sample,Contra,Group) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
      geom_rect(xmin = NtStart, xmax = NtEnd, ymin = Inf, ymax = 0, fill = "lemonchiffon") +
    geom_rect(data = . %>% filter(Stimulus  == "Distractor (Target mid)"),xmin = PdStart, xmax = PdEnd, ymin = -Inf, ymax = 0, fill = "lemonchiffon") +
    geom_line(aes(colour = Session),size=3) +
    scale_color_manual(values=c("black", "royalblue"))+
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(Group~Stimulus) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(10, "lines"), 
          text= element_text(size=50),
          legend.position = "None")
ggsave("search3.pdf", width = 40, height = 20)

allData %>%
  filter(Event == "Learn",  LatStim != "None", Subject != 20, Subject !=16) %>%
  mutate(sample = sample-baseline) %>%
  group_by(sample,Contra) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_rect(xmin = 150, xmax = 250, ymin = Inf, ymax = 0, fill = "mistyrose1") +
    geom_rect(xmin = 250, xmax = 350, ymin = -Inf, ymax = 0, fill = "mistyrose1") +
    geom_line(size=3) +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(10, "lines"), text= element_text(size=12))

allData %>%
  filter(Event == "Search",  LatStim != "None", Subject != 20, Subject !=16) %>%
  mutate(sample = sample-baseline) %>%
  group_by(sample,Contra) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_rect(xmin = 200, xmax = 275, ymin = Inf, ymax = 0, fill = "mistyrose1") +
    geom_rect(xmin = 275, xmax = 350, ymin = -Inf, ymax = 0, fill = "mistyrose1") +
    geom_line(size=3) +
    scale_colour_brewer(palette = "Set1") +
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    geom_vline(xintercept = 0,linetype = "dashed" ) +
    geom_hline(yintercept = 0,linetype = "dashed") +
    theme_apa() +
    theme(panel.spacing.y = unit(10, "lines"), text= element_text(size=12))
```

```{r}
allData %>%
    filter(Event == "Search",  LatStim != "None", Stimulus != "Target (None mid)", Subject != 20, Subject !=16, Group == "Colour-Colour" | Group == "Shape-Shape") %>%
    mutate(sample = sample-baseline) %>%
    group_by(Session, Stimulus,sample,Contra,Group) %>%
    summarise(mean = mean(voltage)) %>%
    spread(Contra, mean) %>% 
    mutate(diff = Contralateral - Ipsilateral) %>%
    ggplot(., aes(sample,diff)) +
    geom_rect(xmin = NtStart, xmax = NtEnd, ymin = Inf, ymax = 0, fill = "lemonchiffon") +
    geom_rect(data = . %>% filter(Stimulus  == "Distractor (Target mid)"),xmin = PdStart, xmax = PdEnd, ymin = -Inf, ymax = 0, fill = "lemonchiffon") +
    geom_vline(xintercept = 0,aes(colour= "gray") ) +
    geom_hline(yintercept = 0,aes(colour= "gray") ) +
    #geom_line( aes(colour = interaction(Group,Session)),size=3) +
    geom_line(data = . %>% filter(Session == "Day1"), aes(colour = Group),size=3) +
    #geom_line(data = . %>% filter(Session == "Day3"), aes(colour = Group),linetype="dashed",size=3) +
    scale_color_manual(values=c("seagreen3", "gray52"))+
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0), limits=c(-200, 500), breaks=seq(-200,500,50)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(.~Stimulus, labeller = labeller(Stimulus = c("Target (Distractor mid)" = "Target","Distractor (Target mid)" = "Distractor"))) +
    theme_apa() +
    theme(panel.spacing.x = unit(10, "lines"), 
          text= element_blank(),
          strip.text.y = element_blank(),
          strip.text.x = element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          legend.position = "None")
ggsave("posterDay1.pdf", width = 30, height = 8)

allData %>%
    filter(Event == "Search",  LatStim != "None", Stimulus != "Target (None mid)", Subject != 20, Subject !=16, Group == "Colour-Colour" | Group == "Shape-Shape") %>%
    mutate(sample = sample-baseline) %>%
    group_by(Session, Stimulus,sample,Contra,Group) %>%
    summarise(mean = mean(voltage)) %>%
    spread(Contra, mean) %>% 
    mutate(diff = Contralateral - Ipsilateral) %>%
    ggplot(., aes(sample,diff)) +
    geom_rect(xmin = NtStart, xmax = NtEnd, ymin = Inf, ymax = 0, fill = "lemonchiffon") +
    geom_rect(data = . %>% filter(Stimulus  == "Distractor (Target mid)"),xmin = PdStart, xmax = PdEnd, ymin = -Inf, ymax = 0, fill = "lemonchiffon") +
    geom_vline(xintercept = 0,aes(colour= "gray") ) +
    geom_hline(yintercept = 0,aes(colour= "gray") ) +
    geom_line( aes(colour = interaction(Group,Session)),size=3) +
    #geom_line(data = . %>% filter(Session == "Day1"), aes(colour = Group),size=3) +
    #geom_line(data = . %>% filter(Session == "Day3"), aes(colour = Group),linetype="dashed",size=3) +
    scale_color_manual(values=c("seagreen3", "gray52", "seagreen4", "gray42"))+
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0), limits=c(-200, 500), breaks=seq(-200,500,50)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(.~Stimulus, labeller = labeller(Stimulus = c("Target (Distractor mid)" = "Target","Distractor (Target mid)" = "Distractor"))) +
    theme_apa() +
    theme(panel.spacing.x = unit(10, "lines"), 
          text= element_blank(),
          strip.text.y = element_blank(),
          strip.text.x = element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          legend.position = "None")
ggsave("posterTrainingEffect.pdf", width = 30, height = 8)

allData %>%
  filter(Event == "Search",  LatStim != "None", Stimulus != "Target (None mid)", Subject != 20, Subject !=16, Session == "Day3") %>%
  mutate(sample = sample-baseline) %>%
  group_by(Session, Stimulus,sample,Contra,GroupP,Group2) %>%
  summarise(mean = mean(voltage)) %>%
  spread(Contra, mean) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  ggplot(., aes(sample,diff)) +
    geom_rect(xmin = NtStart, xmax = NtEnd, ymin = Inf, ymax = 0, fill = "lemonchiffon") +
    geom_rect(data = . %>% filter(Stimulus  == "Distractor (Target mid)"),xmin = PdStart, xmax = PdEnd, ymin = -Inf, ymax = 0, fill = "lemonchiffon") +
    geom_vline(xintercept = 0) +
    geom_hline(yintercept = 0) +
    geom_line(aes(colour = GroupP),size=3) +
    scale_color_manual(values=c("navyblue", "dodgerblue"))+
    scale_x_continuous(name ="Latency (ms)", expand = c(0, 0), limits=c(-200, 500), breaks=seq(-200,500,50)) +
    scale_y_reverse(name =expression(paste("Amplitude (",mu,"v)")), expand = c(0, 0)) +
    facet_grid(Group2~Stimulus, labeller = labeller(Stimulus = c("Target (Distractor mid)" = "Target","Distractor (Target mid)" = "Distractor"))) +
    theme_apa() +
    theme(panel.spacing.x = unit(10, "lines")
          ,text= element_blank()
          ,legend.position = "None"
          ,strip.text.y = element_blank()
          ,strip.text.x = element_blank()
          ,axis.title.x=element_blank()
          ,axis.title.y=element_blank()
          ,axis.text.x=element_text(vjust = 10)
          )
ggsave("posterRetrainEffect.pdf", width = 30, height = 8)

```

```{r PDBehaviour}
PDAmp <- allData %>%
  filter(Event == "Search", Subject != 20 & Subject != 16 & Subject != 37 & Subject != 38 & Subject != 39, Stimulus == "Distractor (Target mid)") %>%
  mutate(sample = sample-baseline) %>%
  filter(sample>PdStart & sample <PdEnd) %>%
  group_by(Session,Subject,Contra,Group, Stimulus) %>%
  summarise(mV = mean(voltage)) %>%
  spread(Contra, mV) %>% 
  mutate(diff = Contralateral - Ipsilateral) %>%
  arrange(Subject)
distBehav <- behavData %>%
  filter(Procedure == "TaskC", Session != 2, CompSearch.ACC==1,Subject != 20 & Subject != 16) %>%
  mutate(Session = as.factor(Session), CompCond = ifelse(LateralityComp=="TC" | LateralityComp=="TL","TO", "TD")) %>%
  group_by(Group, Session, CompCond, Subject) %>%
  summarise(ResponseTime = mean(CompSearch.RT)) %>%
  spread(CompCond, ResponseTime) %>%
  mutate(DistractorInterference = TD - TO) %>%
  arrange(Subject)
pdBehav <- cbind(PDAmp,distBehav)

#Pd in general related to distractor costs in general
cor.test(pdBehav$diff, pdBehav$DistractorInterference)
pdBehav %>%
  ggplot( aes(x=DistractorInterference,y=diff, colour = Session, group = Subject)) +
  geom_point(data = . %>% filter(Group == "Colour-Colour"),shape = 16,size = 5) +
  geom_point(data = . %>% filter(Group == "Colour-Shape"),shape = 17,size = 5) +
  geom_point(data = . %>% filter(Group == "Shape-Colour"),shape = 15,size = 5) +
  geom_point(data = . %>% filter(Group == "Shape-Shape"),shape = 18,size = 5) +
  theme_apa() +
  theme(text= element_blank(),
          strip.text.y = element_blank(),
          strip.text.x = element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          legend.position = "None")
pdBehav %>%
  ggplot( aes(x=DistractorInterference,y=diff, colour = interaction(Session,Group))) +
  geom_smooth(data = . %>% filter(Group == "Colour-Colour"),method = "lm", se=FALSE) +
  geom_smooth(data = . %>% filter(Group == "Colour-Shape"),method = "lm", se=FALSE) +
  geom_smooth(data = . %>% filter(Group == "Shape-Colour"),method = "lm", se=FALSE) +
  geom_smooth(data = . %>% filter(Group == "Shape-Shape"),method = "lm", se=FALSE) +
  theme_apa() +
  theme(text= element_blank(),
          strip.text.y = element_blank(),
          strip.text.x = element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          legend.position = "None")
pdBehav %>%
  filter(Group=="Colour-Colour") %>%
  ggplot( aes(x=DistractorInterference,y=diff, colour = Session, group = Subject)) +
  geom_point(size = 4) +
  geom_line(aes(colour = Group))+
  theme_apa()
pdBehav %>%
  filter(Group=="Shape-Shape") %>%
  ggplot( aes(x=DistractorInterference,y=diff, colour = Session, group = Subject)) +
  geom_point(size = 4) +
  geom_line(aes(colour = Group))+
  theme_apa()
pdBehav %>%
  filter(Group=="Shape-Colour") %>%
  ggplot( aes(x=DistractorInterference,y=diff, colour = Session, group = Subject)) +
  geom_point(size = 4) +
  geom_line(aes(colour = Group))+
  theme_apa()
pdBehav %>%
  filter(Group=="Colour-Shape") %>%
  ggplot( aes(x=DistractorInterference,y=diff, colour = Session, group = Subject)) +
  geom_point(size = 4) +
  geom_line(aes(colo4ur = Group))+
  theme_apa()

pdBehav %>%
  filter(Session=="Day1") %>%
  ggplot( aes(x=DistractorInterference,y=diff, colour = Session, group = Subject)) +
  geom_point() +
  geom_line()+
  theme_apa()+
  theme(legend.position = "None")
pdBehav %>%
  filter(Session=="Day3") %>%
  ggplot( aes(x=DistractorInterference,y=diff, colour = Session, group = Subject)) +
  geom_point() +
  geom_line()+
  theme_apa()+
  theme(legend.position = "None")

#Pd diff across sessions related to cost diff across sessions
PDAmp <- PDAmp %>% select(-c(Stimulus,Contralateral,Ipsilateral)) %>% spread(Session, diff)
PDAmp$pdXsess = PDAmp$Day1 - PDAmp$Day3
distBehav <- distBehav %>% select(-c(TD,TO)) %>% spread(Session, DistractorInterference) 
distBehav$costXsess = distBehav$`1`- distBehav$`3`

cor.test(PDAmp$pdXsess,distBehav$costXsess)

PDAmp <- cbind(PDAmp,distBehav)
PDAmp %>%
  ggplot(aes(x = costXsess, y = pdXsess)) +
  geom_point() +
  theme_apa()
```

```{r searchStats}
#Nt
nt.search.day1 <- allData %>%
  filter(Event == "Search", Session == "Day1", LatStim != "None", Subject != 20, Subject !=16) %>%
  mutate(sample = sample-baseline) %>%
  filter(sample>NtStart & sample <NtEnd) %>%
  group_by(Stimulus,Subject,Contra,Group1) %>%
  summarise(mV = mean(voltage)) %>%
  spread(Contra, mV) %>% 
  mutate(diff = Contralateral - Ipsilateral)

nt.search.day1.aov <- aov_ez(data = nt.search.day1,
                            dv = "diff",
                            id = "Subject",
                            within = c("Stimulus"),
                            between = c("Group1")
                            )
#nt.learn.day1.results <- apa_print(nt.learn.day1.aov)
nt.search.day1.emmeans <- emmeans(nt.search.day1.aov, ~Group1*Stimulus)
nt.search.day1.posthoc <- pairs(nt.search.day1.emmeans)


pd.search.day1 <- allData %>%
  filter(Event == "Search", Session == "Day1", LatStim != "None", Subject != 20, Subject !=16) %>%
  mutate(sample = sample-baseline) %>%
  filter(sample>PdStart & sample <PdEnd) %>%
  group_by(Stimulus,Subject,Contra,Group1) %>%
  summarise(mV = mean(voltage)) %>%
  spread(Contra, mV) %>% 
  mutate(diff = Contralateral - Ipsilateral)

pd.search.day1.aov <- aov_ez(data = pd.search.day1,
                            dv = "diff",
                            id = "Subject",
                            within = c("Stimulus"),
                            between = c("Group1")
                            )
#pd.learn.day1.results <- apa_print(pd.learn.day1.aov)


nt.search.TO <- allData %>%
  filter(Event == "Search", Stimulus == "Target (None mid)", Subject != 20 & Subject != 16) %>%
  mutate(sample = sample-baseline) %>%
  filter(sample>NtStart & sample <NtEnd) %>%
  group_by(Session,Subject,Contra,Group1, GroupP) %>%
  summarise(mV = mean(voltage)) %>%
  spread(Contra, mV) %>% 
  mutate(diff = Contralateral - Ipsilateral)
nt.search.aov.TO <- aov_ez(data = nt.search.TO,
                            dv = "diff",
                            id = "Subject",
                            within = c("Session"),
                            between = c("Group1", "GroupP")
                            )


nt.search.TD <- allData %>%
  filter(Event == "Search", Stimulus == "Target (Distractor mid)", Subject != 20 & Subject != 16) %>%
  mutate(sample = sample-baseline) %>%
  filter(sample>NtStart & sample <NtEnd) %>%
  group_by(Session,Subject,Contra,Group1, GroupP) %>%
  summarise(mV = mean(voltage)) %>%
  spread(Contra, mV) %>% 
  mutate(diff = Contralateral - Ipsilateral)
nt.search.TD.aov <- aov_ez(data = nt.search.TD,
                            dv = "diff",
                            id = "Subject",
                            within = c("Session"),
                            between = c("Group1", "GroupP")
                            )

pd.search.DT <- allData %>%
  filter(Event == "Search", Stimulus == "Distractor (Target mid)", Subject != 20 & Subject != 16) %>%
  mutate(sample = sample-baseline) %>%
  filter(sample>PdStart & sample <PdEnd) %>%
  group_by(Session,Subject,Contra,Group1, GroupP) %>%
  summarise(mV = mean(voltage)) %>%
  spread(Contra, mV) %>% 
  mutate(diff = Contralateral - Ipsilateral)
pd.search.DT.aov <- aov_ez(data = pd.search.DT,
                            dv = "diff",
                            id = "Subject",
                            within = c("Session"),
                            between = c("Group1", "GroupP")
                            )
pd.search.emmeans <- emmeans(pd.search.DT.aov, ~Group1*Session)
pd.search.posthoc <- pairs(pd.search.emmeans)
```